language: cpp
sudo: false
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: BUILD_SYSTEM=bazel
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - wget
            - libjpeg-progs
            - netpbm
            - oracle-java8-installer

    - os: osx
      env: BUILD_SYSTEM=bazel

    - os: linux
      dist: trusty
      env: BUILD_SYSTEM=make
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - wget
            - libpng-dev
            - pkg-config
            - libjpeg-progs
            - netpbm

    - os: osx
      env: BUILD_SYSTEM=make


install:
- jdk_switcher use oraclejdk8
- ./.travis.sh install
script:
- ./.travis.sh script
